---
- name: Dra ner image, starta postgres databas mha docker volume, kör imagen
  hosts: localhost

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Pull Docker image
      shell: "docker pull bugzapper/iss-app-cicd:latest"

    - name: Run PostgreSQL Docker container
      shell: "docker run --rm -e POSTGRES_PASSWORD=pass -e POSTGRES_USER=awesome -e POSTGRES_DB=iss-db -p 5432:5432 -v pgdata:/var/lib/postgresql/data -d postgres"

    - name: Run appens Docker Image som nyss laddades ner
      shell: "docker run -p 3000:3000 -e PG_HOST={{ ansible_default_ipv4.address }} -d bugzapper/iss-app-cicd:latest" # Anänder serberns IPv4-Adress oavsett adress

- name: Hello World Playbook
  hosts: localhost
  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello, World!"
